language: c

addons:
  postgresql:
    - 11
  apt:
    packages:
      - postgresql-server-dev-11
      - libprotobuf-c0-dev
      - libprotobuf-c0
      - protobuf-c-compiler
      - zlib1g-dev
      - zlib1g
      - libjson-c-dev
      - libjson-c2
      - python-setuptools
      - libtap-parser-sourcehandler-pgtap-perl
      - postgresql-11-pgtap

before_install:
  - sudo service postgresql stop
  - sudo pg_ctlcluster 11 main start
  - sudo pg_lsclusters

install:
  - sudo -u postgres psql -c 'CREATE DATABASE osm_test_db;'
  - psql -d osm_test_db -c 'CREATE EXTENSION pgtap;'

before_script:
  - sudo make install

script:
  - make test TEST_PORT=5432 TEST_DATABASE=osm_test_db
